ALTER TABLE inventory ADD COLUMN IF NOT EXISTS refund_status VARCHAR(20) DEFAULT NULL;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS refund_date DATE DEFAULT NULL;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS refund_amount INTEGER DEFAULT NULL;
